name: DhikrCounter
options:
  bundleIdPrefix: com.fuutaworks
  deploymentTarget:
    iOS: 16.0
    watchOS: 10.0
  developmentLanguage: en

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"

targets:
  # iPhone App Target
  DhikrCounter:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: DhikrCounter
      - path: Shared
    resources:
      - DhikrCounter/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fuutaworks.DhikrCounter"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SKIP_INSTALL: false
        TARGETED_DEVICE_FAMILY: "1,2"
    dependencies:
      - sdk: WatchConnectivity.framework
      - sdk: Foundation.framework
      - sdk: SwiftUI.framework

  # Apple Watch App Target
  "DhikrCounter Watch App":
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: "DhikrCounter Watch App"
      - path: Shared
    resources:
      - "DhikrCounter Watch App/Assets.xcassets"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fuutaworks.DhikrCounter.watchkitapp"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SKIP_INSTALL: false
        TARGETED_DEVICE_FAMILY: "4"
    dependencies:
      - sdk: WatchConnectivity.framework
      - sdk: WatchKit.framework
      - sdk: SwiftUI.framework
      - sdk: CoreMotion.framework

schemes:
  DhikrCounter:
    build:
      targets:
        DhikrCounter: all
        "DhikrCounter Watch App": all
    run:
      config: Debug
    archive:
      config: Release
      
  "DhikrCounter Watch App":
    build:
      targets:
        "DhikrCounter Watch App": all
    run:
      config: Debug