name: DhikrCounterWatch
options:
  bundleIdPrefix: com.fuutaworks
  deploymentTarget:
    watchOS: 10.0
  developmentLanguage: en

settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"

targets:
  "DhikrCounterWatch":
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: "DhikrCounter Watch App"
      - path: Shared
    resources:
      - "DhikrCounter Watch App/Assets.xcassets"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fuutaworks.DhikrCounterWatch"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SKIP_INSTALL: false
        TARGETED_DEVICE_FAMILY: "4"

schemes:
  DhikrCounterWatch:
    build:
      targets:
        DhikrCounterWatch: all
    run:
      config: Debug