# TKEO Configuration for Periodic Pinch Detection
# Optimized for sessions with setup periods and high-magnitude contamination

tkeo_params:
  # Sampling and filtering
  fs: 50  # Sampling frequency - matches your data
  bandpass_low: 1.0  # Lower cutoff to catch slower pinch patterns
  bandpass_high: 8.0  # Lower high cutoff to reject rapid hand movements
  
  # More adaptive baseline tracking for varying activity levels
  baseline_alpha: 0.05  # Faster adaptation to changing baseline
  hampel_k: 4.0  # More robust against outliers (high-magnitude events)
  
  # More permissive gate thresholds for periodic detection
  gate_k_accel: 2.5  # Lower threshold for better sensitivity
  gate_k_gyro: 2.5   # Lower threshold for better sensitivity  
  gate_k_fusion: 2.5 # Lower fusion threshold
  
  # Sensor fusion with balanced weights
  fusion_method: 'additive'
  fusion_weight_accel: 1.2  # Slightly higher accel weight
  fusion_weight_gyro: 1.0   # Lower gyro weight to reduce movement artifacts
  
  # More permissive template verification
  template_length: 12  # Shorter templates (120ms) for faster pinches
  template_confidence: 0.45  # Much lower threshold to catch more events
  
  # Shorter refractory period for rapid sequences
  refractory_period_s: 0.200  # Allow faster pinch sequences (200ms)
  verification_window_s: 0.12  # Shorter window matching template length

# Optimizations for periodic pinch data:
# - Lower frequency range (1-8 Hz) focuses on deliberate gestures
# - More adaptive baseline handles varying activity levels
# - Permissive thresholds catch subtle periodic patterns
# - Shorter refractory period allows rapid sequences
# - Lower template confidence reduces false rejections